version: "3"

services:
  main:
    build: ./api
    image: mapachapo.azurecr.io/main:latest
    restart: always
    ports:
      - "5000:5000"
    networks:
      - mapachaonetwork 
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app/media
networks:
  mapachaonetwork:
    driver: bridge
