# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: |
          npm install
          npm run dev-install
      - name: Build Back
        run: "echo 'Not implemented'"
      - name: Test Back
        run: "echo 'Not implemented'"
      - name: Build UI
        run: "echo 'Not implemented'"
      - name: Test UI
        run: "echo 'Not implemented'"
