# This is a basic workflow to help you get started with Actions

name: CICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: |
          npm install
          npm run dev-install
      - name: Build Back
        run: "echo 'Not implemented'"
      - name: Test Back
        run: "echo 'Not implemented'"
      - name: Build UI
        run: "echo 'Not implemented'"
      - name: Test UI
        run: "echo 'Not implemented'"
  deploy:
    name: Deploy to ACR
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      # Client
      - name: Docker build client
        run: docker build . -t mapachapo.azurecr.io/client:${{ github.sha }} --compress -f client/Dockerfile
      - name: Docker push
        run: docker push mapachapo.azurecr.io/client:${{ github.sha }}
      # API
      - name: Docker build client
        run: docker build . -t mapachapo.azurecr.io/api:${{ github.sha }} --compress -f api/Dockerfile
      - name: Docker push
        run: docker push mapachapo.azurecr.io/api:${{ github.sha }}
      # Main
      - name: Docker build
        run: docker build . -t mapachapo.azurecr.io/main:${{ github.sha }}
      - name: Docker push
        run: docker push mapachapo.azurecr.io/main:${{ github.sha }}
