# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build_deploy:
    name: Build, test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: npm run dev-install
      - name: Build Back
        run: "echo 'Not implemented'"
      - name: Test Back
        run: "echo 'Not implemented'"
      - name: Build UI
        run: "echo 'Not implemented'"
      - name: Test UI
        run: "echo 'Not implemented'"
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Docker build
        run: docker build . -t ${{ secrets.ACR_URL }}/${{ ACR_TAG }}:${{ github.sha }}
      - name: Docker push
        run: docker push ${{ secrets.ACR_URL }}/${{ ACR_TAG }}:${{ github.sha }}
