name: CI
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.1'
      # Build and test API
      - name: Install API all depenendies
        run: |
          cd api/
          pwd
          npm install
      - name: Build API
        run: npm run api-lint
      - name: Test API
        run: npm run api-test
      # Build and test UI
      - name: Install UI all depenendies
        run: |
          cd client/
          pwd
          npm install
      - name: Build UI
        run: |
          cd client/
          pwd
          npm run build
      - name: Test UI
        run: echo 'not implemented'
